# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Path Of D
email: d.majard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bringing more science to your company. Hire me to become more data driven and make decisions
  that will impact your success for good!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.thepathofd.com" # the base hostname & protocol for your site
twitter_username: Mahrard
github_username:  Mahrard
kaggle_username:  thepathofd

# Build settings
markdown: kramdown
