# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 'LeData.Science'
email: d.majard@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bring more science to your company. Become more data driven and make decisions
  that will impact your success for good!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.ledata.science" # the base hostname & protocol for your site
twitter_username: LeData_science
github_username:  LeData
kaggle_username:  thepathofd
linkedin_username: dany-majard
cv: Dec2017
google_analytics: UA-111318742-1
publish: True

# Build settings
markdown: kramdown

sass:
    load_paths:
        - _sass
        - node_modules
exclude: []

#gems:
#  - jekyll-jupyter-notebook
#
# then in the html:
#Remember to run "$chcp 65001" in the shell before running jekyll serve.
#{::nomarkdown}
#{% jupyter_notebook Detroit-Blight-1.ipynb %}
#{:/nomarkdown}